name: Deploy a new release
on:
  release:
    types:
      - published

jobs:
  release:
    name: Release the new version
    runs-on: ubuntu-20.04
    environment: release
    steps:
      - uses: actions/checkout@v3
      - name: Run release script
        run: ./scripts/release.sh
        env:
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_FORMAT: ${{ secrets.PRIVATE_KEY_FORMAT }}
          PRIVATE_KEY_PASSPHRASE: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
