name: Deploy a new release
on:
  release:
    types:
      - published
  push: null

jobs:
  release:
    name: Release the new version
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/release.sh